100-hours-a-week/14-YG-FE

- package-lock.json
- package.json
- src/App.styled.ts
- src/Router.tsx
- src/components/common/SectionLine.styled.ts
- src/components/common/button/Button.styled.ts
- src/components/common/button/Button.tsx
- src/components/common/inputField/InputField.styled.ts
- src/components/common/inputField/InputField.tsx
- src/components/main/subSection/SubSection.styled.ts
- src/pages/postDetail/PostDetail.styled.ts
- src/pages/signup/Signup.styled.ts
- src/pages/signup/Signup.tsx
- src/schemas/signupSchema.ts
> [feat] : 회원가입 페이지 ui 구현

- src/components/common/filteringSelector/FilteringSelector.styled.ts
- src/components/common/filteringSelector/FilteringSelector.tsx
- src/components/common/image/imageContainer/ImageContainer.styled.ts
- src/components/common/input/controlledNumberInput/ControlledNumberInput.tsx
- src/components/common/myList/MyList.styled.ts
- src/components/common/myList/MyList.tsx
- src/components/common/myList/myListCard/MyListCard.tsx
- src/components/common/profile/Profile.styled.ts
- src/components/common/profile/Profile.tsx
- src/components/main/subSection/SubSection.tsx
- src/components/writePost/unitAmountSelector/UnitAmountSelector.tsx
- src/hooks/mutations/order/useCancelOrderMutation.ts
- src/pages/mypage/Mypage.styled.ts
- src/pages/postDetail/PostDetail.tsx
- src/pages/writePost/WritePost.tsx
- src/schemas/writePostSchema.ts
- src/types/orderType.ts
- src/utils/input.ts
> [feat] : 공구글 작성 페이지 유효성 검사 추가 및 마이페이지 api 연동 완료

- src/api/host.ts
- src/api/product.ts
- src/components/main/subSection/SubSection.tsx
- src/components/main/topSection/TopSection.tsx
- src/hooks/mutations/host/useGetAIMutation.ts
- src/pages/writePost/WritePost.tsx
- src/types/hostType.ts
- src/types/productType.ts
> [feat] : AI api 로직 구현

- src/components/common/input/dateInput/DateInput.styed.ts
- src/components/common/input/dateInput/DateInput.tsx
- src/components/common/input/selectButtonInput/SelectButtonInput.tsx
- src/components/common/loading/Loading.Style.ts
- src/components/writePost/unitAmountSelector/UnitAmountSelector.tsx
- src/hooks/mutations/host/useGetAIMutation.ts
- src/pages/signup/Signup.tsx
- src/pages/writePost/WritePost.tsx
[관련 이슈]
#21 #25 
- 수량 선택 시 폼 리렌더링 문제 해결
- 드롭다운 리팩토링
- 달력 잘리는 문제 해결
- ai 기능 추가
> [feat] : ai 기능 수정 및 리팩토링

- src/App.tsx
- src/hooks/queries/useMyInfoQuery.ts
- src/pages/main/Main.tsx
> [fix] : 새로고침 시 로그아웃 문제 해결

- src/pages/postDetail/PostDetail.tsx
[fix] : 마감 종료 시 새로고침 / 콘솔 메세지 제거
> [fix] : 마감 종료 시 새로고침 / 콘솔 메세지 제거

- src/Router.tsx
- src/components/chatList/chatCard/ChatCard.styled.ts
- src/components/chatList/chatCard/ChatCard.tsx
- src/components/common/myList/myListCard/MyListCard.styled.ts
- src/components/common/myList/myListCard/MyListCard.tsx
- src/pages/chatList/ChatList.styled.ts
- src/pages/chatList/ChatList.tsx
- src/styles/Colors.ts
> [feat] : 채팅 리스트 페이지 ui 구현

- src/api/host.ts
- src/api/order.ts
- src/api/user.ts
- src/components/common/image/imageContainer/ImageContainer.styled.ts
- src/components/common/image/imageContainer/ImageContainer.tsx
- src/components/common/likeToggle/LikeToggle.styled.ts
- src/components/common/likeToggle/LikeToggle.tsx
- src/components/common/myList/MyList.styled.ts
- src/components/common/myList/MyList.tsx
- src/components/common/myList/myListCard/MyListCard.tsx
- src/components/main/mainCard/MainCard.tsx
- src/components/main/subSection/SubSection.tsx
- src/components/mypage/filteringTab/FilteringTab.styled.ts
- src/components/mypage/filteringTab/FilteringTab.tsx
- src/hooks/mutations/user/useLikeMutation.ts
- src/hooks/queries/useHostList.ts
- src/pages/mypage/Mypage.tsx
- src/stores/useLikeStore.ts
- src/types/orderType.ts
- src/types/userType.ts
> [feat] : 마이페이지 ui 업그레이드

- src/components/common/header/Header.tsx
- src/components/common/image/imageSlider/ImageSlider.tsx
- src/components/common/likeToggle/LikeToggle.styled.ts
- src/components/common/likeToggle/LikeToggle.tsx
- src/components/common/modal/loginModal/LoginModal.stlyed.ts
- src/components/postList/productCard/ProductCard.tsx
- src/pages/postDetail/PostDetail.tsx
> [feat] : postList 좋아요 기능 추가

- src/assets/icons/Etc.svg
- src/components/common/profile/Profile.styled.ts
- src/components/common/profile/Profile.tsx
- src/components/postDetail/dropDownMenu/DropDownMenu.styled.ts
- src/components/postDetail/dropDownMenu/DropDownMenu.tsx
- src/components/writePost/postForm/PostForm.tsx
> [refactor] : 상세페이지 드롭다운메뉴 추가

- src/App.styled.ts
- src/App.tsx
- src/Router.tsx
- src/api/chat.ts
- src/components/chatList/chatCard/ChatCard.tsx
- src/components/common/masterButton/MasterButton.styled.ts
- src/components/common/masterButton/MasterButton.tsx
- src/pages/chatRoom/ChatRoom.styled.ts
- src/pages/chatRoom/ChatRoom.tsx
> [api] : chat api 로직 구현

- src/api/user.ts
- src/components/common/image/imageUploader/ImageUploader.styled.ts
- src/components/common/image/imageUploader/ImageUploader.tsx
- src/components/common/profile/Profile.styled.ts
- src/components/common/profile/Profile.tsx
- src/hooks/mutations/user/usePatchProfileImgMutation.ts
- src/pages/signupInfo/SignupInfo.tsx
- src/types/userType.ts
> [refactor] : 마이페이지 이미지 수정 구현

- src/api/instance.ts
- src/api/product.ts
- src/api/user.ts
- src/components/common/filteringSelector/FilteringSelector.styled.ts
- src/components/common/filteringSelector/FilteringSelector.tsx
- src/components/common/image/imageUploader/ImageUploader.tsx
- src/components/common/profile/Profile.tsx
- src/components/common/toast/Toast.styled.ts
- src/components/main/subSection/SubSection.tsx
- src/hooks/mutations/user/usePatchProfileImgMutation.ts
- src/hooks/queries/useInfiniteQuery.ts
- src/hooks/queries/useProductQuery.ts
- src/pages/postList/PostList.styled.ts
- src/pages/postList/PostList.tsx
- src/types/productType.ts
> [feat] : 무한스크롤 구현 및 프로필 이미지 수정

- src/App.tsx
- src/components/common/modal/successModal/SuccessModal.tsx
- src/components/mypage/myList/MyList.tsx
- src/hooks/mutations/order/useOrderMutation.ts
- src/stores/useModalStore.ts
> [feat] : 마이페이지 주문상세조회 구현

- .env.dev
- src/components/signup/checkAccount/CheckAccount.styled.ts
- src/components/signup/checkAccount/CheckAccount.tsx
- src/hooks/mutations/user/useCheckAccountMutation.ts
- src/hooks/queries/useCheckAccountQuery.ts
- src/schemas/signupInfoSchema.ts
> [fix] : 폼 중첩문제 해결

- src/components/chat/ChatBox.styled.ts
- src/components/chat/ChatBox.tsx
- src/pages/chatRoom/ChatRoom.styled.ts
- src/pages/chatRoom/ChatRoom.tsx
> [feat] : 채팅 ui 수정

- src/hooks/queries/useInfiniteQuery.ts
- src/pages/postList/PostList.styled.ts
- src/pages/postList/PostList.tsx
> [fix] : 무한스크롤 수정

- src/App.tsx
- src/api/chat.ts
- src/components/chat/ChatBox.styled.ts
- src/components/chat/ChatBox.tsx
- src/components/writePost/postForm/PostForm.tsx
- src/hooks/useCurrentMessagePolling.ts
- src/pages/chatRoom/ChatRoom.tsx
- src/types/chatType.ts
> [feat] : 채팅 롱폴링 구현

- src/api/host.ts
- src/components/common/dotText/DotText.styled.ts
- src/components/common/modal/Modal.Style.ts
- src/components/common/modal/confirmModal/ConfirmModal.tsx
- src/components/common/modal/hostModal/HostModal.styled.ts
- src/components/common/modal/hostModal/HostModal.tsx
- src/components/common/modal/successModal/SuccessModal.tsx
- src/hooks/mutations/host/usePatchOrderStatusMutation.ts
- src/hooks/queries/useInfiniteQuery.ts
- src/types/hostType.ts
- src/types/productType.ts
> [refactor] : 참여자 확인 모달 취소자 추가 및 ui 수정 & 주문 상세 모달 첫 렌더링 깨지는 문제 해결

- src/Router.tsx
- src/api/chat.ts
- src/api/user.ts
- src/hooks/queries/useChatQuery.ts
- src/hooks/queries/useKakaoLoginQuery.ts
- src/pages/KakaoCallback.tsx
- src/types/chatType.ts
> [feat] : 카카오로그인 리다이렉트 페이지 구현

- src/components/writePost/postForm/PostForm.tsx
- src/hooks/mutations/host/useGetAIMutation.ts
- src/pages/editMyInfo/EditMyInfo.styled.ts
- src/types/hostType.ts
> [refactor] : ai 답변 마감, 픽업일자 추가

- package-lock.json
- package.json
- src/api/chat.ts
- src/hooks/queries/useChatQuery.ts
- src/pages/chatRoom/ChatRoom.tsx
- src/types/chatType.ts
> [refactor] : 채팅 무한스크롤 구현

- src/api/chat.ts
- src/hooks/queries/useChatQuery.ts
- src/pages/chatList/ChatList.tsx
- src/types/chatType.ts
> [fix] : 채팅 리스트 무한스크롤 구현

- src/components/common/profile/Profile.tsx
- src/pages/chatRoom/ChatRoom.tsx
> [fix] : 상세페이지 계좌복사 수정

- src/api/user.ts
- src/components/common/profile/Profile.tsx
- src/hooks/queries/useMyInfoQuery.ts
- src/pages/chatRoom/ChatRoom.tsx
> [fix] : 채팅 무한렌더링 수정 및 토큰 재발급 로직 추가

- src/hooks/mutations/order/useOrderMutation.ts
- src/hooks/queries/useChatQuery.ts
- src/hooks/useCurrentMessagePolling.ts
- src/pages/chatRoom/ChatRoom.styled.ts
- src/pages/chatRoom/ChatRoom.tsx
> [fix] : 채팅 롱폴링 연결 유지 및 버그 수정

- src/api/chat.ts
- src/hooks/mutations/order/useOrderMutation.ts
- src/hooks/queries/useChatQuery.ts
- src/hooks/queries/usePartiListQuery.ts
- src/pages/KakaoCallback.tsx
- src/pages/chatRoom/ChatRoom.styled.ts
- src/pages/chatRoom/ChatRoom.tsx
> [refactor] : 채팅 오류 공지 및 qa 반영

- src/Router.tsx
- src/api/chat.ts
- src/components/chat/chatRoomUI/ChatRoomUI.styled.ts
- src/components/chat/chatRoomUI/ChatRoomUI.tsx
- src/components/mypage/myListCard/MyListCard.tsx
- src/components/postDetail/anonymousChatPreview/AnonymousChatPreview.styled.ts
- src/components/postDetail/anonymousChatPreview/AnonymousChatPreview.tsx
- src/hooks/queries/useAnonyChatQuery.ts
- src/pages/anonyChatRoom/AnonyChatRoom.styled.ts
- src/pages/anonyChatRoom/AnonyChatRoom.tsx
- src/pages/chatRoom/ChatRoom.tsx
- src/pages/postDetail/PostDetail.tsx
- src/types/chatType.ts
> [refactor] : 채팅방 공통 ui로 분리

- src/components/mypage/myListCard/MyListCard.tsx
- 주문목록 '환불 대기 중' 상태 추가
- 백 hotfix 이후 변경된 사항이 있음
> [HOTFIX] : 주문목록 '환불 대기 중' 상태 추가
